const actionMaps = Object.freeze({
  ADD_TOKEN: "ADD_TOKEN",
  ADD_MERCHANTS: "ADD_MERCHANTS",
  REMOVE_MERCHANT: "REMOVE_MERCHANT",
  SET_MAXCOUNT: "SET_MAXCOUNT",
  SET_PAGE: "SET_PAGE",
  TOGGLE_ADD_DIALOG: "TOGGLE_ADD_DIALOG",
  TOGGLE_EDIT_DIALOG: "TOGGLE_EDIT_DIALOG",
  TOGGLE_SNACKBAR: "TOGGLE_SNACKBAR",
  SET_EDIT: "SET_EDIT",
  SET_MESSAGE: "SET_MESSAGE",
  ADD_CARDS: "ADD_CARDS",
  SET_CARD_PAGE: "SET_CARD_PAGE",
  REMOVE_CARD: "REMOVE_CARD",
  SET_CARDS_MAXCOUNT: "SET_CARDS_MAXCOUNT",
  SET_VARIANT: "SET_VARIANT"
});

export default actionMaps;
